version: '3.7'

services:
  my-python-app:
    build: .
    networks:
      - network-zabbix

  zabbix-server:
    image: ${ZABBIX_SERVER_IMAGE:-zabbix/zabbix-server-pgsql:ubuntu-6.4-latest}
    restart: unless-stopped
    ports:
      - "10051:10051"
    volumes:
      - zabbix_data:/var/lib/zabbix
      - zabbix_log:/var/log/zabbix
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - postgres
    networks:
      - network-zabbix

  zabbix-frontend:
    image: ${ZABBIX_FRONTEND_IMAGE:-zabbix/zabbix-web-nginx-pgsql:6.4-ubuntu-latest}
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PHP_TZ: ${TZ}
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
    depends_on:
      - zabbix-server
    networks:
      - network-zabbix

  zabbix-agent:
    image:  ${ZABBIX_AGENT_IMAGE:-zabbix/zabbix-agent:6.4-ubuntu-latest}
    restart: unless-stopped
    ports:
      - "10050:10050"
    environment:
      ZBX_ACTIVE_ALLOW: false
      TZ: ${TZ}
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_HOSTNAME: zabbix-agent
      ZBX_HOSTNAMEITEM: system.hostname
    depends_on:
      - zabbix-server
    networks:
      - network-zabbix

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    volumes:
      - zabbix_web_data:/var/lib/zabbix
  
  zabbix_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:latest}
    restart: unless-stopped
    container_name: postgres
    hostname: Postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./path/to/your/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
    networks:
      - network-zabbix

  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana}
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_SECRET:-12345}
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
      TZ: ${TZ}
    user: "472"
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - zabbix-frontend
    networks:
      - network-zabbix

  

volumes:
    postgres: {}
    grafana: {}
    zabbix_data:
    zabbix_log:
    zabbix_web_data:
    postgres_data:

networks:
  network-zabbix:
    driver: bridge

#db.odbc.select[water_levels,,Driver = /usr/lib/aarch64-linux-gnu/odbc/psqlodbcw.so;Database=zabbix;Server=172.31.0.3;Port=5432]
#select version();