version: '3.7'

services:
  zabbix-server:
    build: ./zabbix_server
    ports:
      - "10051:10051"
    volumes:
      - zabbix_data:/var/lib/zabbix
    environment:
      DB_SERVER_HOST: postgres
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - postgres
    networks:
      - zabbix-network

  zabbix-frontend:
    build: ./zabbix_frontend
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PHP_TZ: Asia/Tokyo
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network


  postgres:
    build: ./database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
    networks:
      - zabbix-network

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: 12345
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
      TZ: Asia/Tokyo
    depends_on:
      - zabbix-frontend
    networks:
      - zabbix-network

volumes:
  zabbix_data:
  postgres_data:

networks:
  zabbix-network:
    driver: bridge
