version: '3.7'

services:
  zabbix-server:
    build: ./zabbix_server
    ports:
      - "10051:10051"
    volumes:
      - zabbix_data:/var/lib/zabbix
    depends_on:
      - postgres
    networks:
      - zabbix-network

  zabbix-frontend:
    build: ./zabbix_frontend
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network


  postgres:
    build: ./database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zabbix-network

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - zabbix-frontend
    networks:
      - zabbix-network

volumes:
  zabbix_data:
  postgres_data:

networks:
  zabbix-network:
    driver: bridge
